FROM docker.m.daocloud.io/library/node:20-bookworm-slim

WORKDIR /app/server

COPY server/package*.json ./
RUN npm config set registry https://registry.npmmirror.com \
  && npm ci

COPY server/ ./
RUN npm run build

RUN mkdir -p data

EXPOSE 5005

CMD ["npm", "start"]
